import React from "react";

export type Project = {
  name: string;
  shortDescription: string | React.ReactNode;
  preview: string;
  slug: string;
  year: number;
  private: boolean;
  priority: boolean;
  developedFor: string;
  role: string;
  tags: string[];
  link?: string;
  detailedInfo?: {
    fullDescription: string | React.ReactNode;
    fillImage: string;
    devices?: {
      desktop: string;
      tablet: string;
      mobile: string;
    };
    gallery?: string[];
  };
  relatedProjects?: string[];
};
const PROJECTS_IMAGES_PATH = "/assets/images/projects/";

export const PROJECTS: Project[] = [
  {
    slug: "st-video",
    name: "SimpleTherapy video application",
    shortDescription:
      "An application for scheduled video meetings between users and their therapist. The application can be used directly from the link or embedded via iframe.",
    preview: PROJECTS_IMAGES_PATH + "/st-video/" + "preview.webp",
    year: 2024,
    private: true,
    priority: true,
    developedFor: "SimpleTherapy inc.",
    role: "Full-stack",
    tags: [
      "TypeScript",
      "Next.js",
      "React",
      "Twilio SDK",
      "Tailwind CSS",
      "Bitbucket",
      "Bitbucket Pipelines",
      "AWS Transcribe",
      "WebSockets",
    ],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/st-video/" + "full.webp",
      fullDescription: (
        <>
          <p>
            <strong>Video application for SimpleTherapy.</strong>
          </p>
          <p>
            An application for scheduled video meetings between users and their therapist. The application can
            be used directly from the link or embedded via iframe.
          </p>
          <p>
            The user can use closed captions during the video call. The closed captions are generated by AWS
            Transcribe service.
          </p>
          <p>
            The application is built on Next.js (React) and uses Twilio SDK for video calls. The application
            is fully responsive and works on all devices.
          </p>
        </>
      ),
      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/st-video/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/st-video/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/st-video/" + "mobile.webp",
      },
    },
    relatedProjects: ["st-website", "st-booking", "st-ref"],
  },
  {
    slug: "st-ref",
    name: "SimpleTherapy referral system",
    shortDescription:
      "A referral system for SimpleTherapy. The system allows users to refer other users to the service.",
    preview: PROJECTS_IMAGES_PATH + "/st-ref/" + "preview.webp",
    year: 2023,
    private: true,
    priority: true,
    developedFor: "SimpleTherapy inc.",
    role: "Front-end",
    tags: ["TypeScript", "React", "REST API", "Bitbucket", "Bitbucket Pipelines", "AWS"],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/st-ref/" + "full.webp",
      fullDescription: (
        <>
          <p>
            <strong>A referral system for SimpleTherapy.</strong>
          </p>
          <p>
            Simple web application that allows users to refer other users to the service. The referred person
            will receive an email with a link to the service and the referral code.
          </p>
        </>
      ),
      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/st-ref/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/st-ref/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/st-ref/" + "mobile.webp",
      },
    },
    relatedProjects: ["st-website", "st-video", "st-booking"],
  },
  {
    slug: "st-booking",
    name: "SimpleTherapy booking system",
    shortDescription:
      "Booking system for SimpleTherapy. The system allows users to book a session with their therapist.",
    preview: PROJECTS_IMAGES_PATH + "/st-booking/" + "preview.webp",
    year: 2022,
    private: true,
    priority: true,
    developedFor: "SimpleTherapy inc.",
    role: "Full-stack",
    tags: ["TypeScript", "Next.js", "React", "Postgres", "Cal.Com", "Google Maps API"],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/st-booking/" + "full.webp",
      fullDescription: (
        <>
          <p>
            <strong>Booking system for SimpleTherapy.</strong>
          </p>
          <p>
            The system allows users to book a session with their therapist. The system is based on open source
            Cal.Com software. The system is customized for the needs of SimpleTherapy (changed the structure
            of database, extended the roles and permissions of the users, integrated custom hooks etc.).
          </p>
        </>
      ),

      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/st-booking/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/st-booking/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/st-booking/" + "mobile.webp",
      },
    },
    relatedProjects: ["st-website", "st-video", "st-ref"],
  },
  {
    slug: "st-website",
    name: "SimpleTherapy website",
    shortDescription:
      "SimpleTherapy company website. The website is designed to be simple and easy to use. It is built with Wordpress and Bootstrap. The website is fully responsive and works on all devices.",
    preview: PROJECTS_IMAGES_PATH + "/st-website/" + "preview.webp",
    year: 2022,
    private: false,
    priority: true,
    developedFor: "SimpleTherapy inc.",
    role: "Full-stack",
    link: "https://simpletherapy.com",
    tags: ["JavaScript", "Wordpress", "Bootstrap", "SCSS", "Webpack", "npm"],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/st-website/" + "full.webp",
      fullDescription: (
        <>
          <p>
            <strong>Website of the SimpleTherapy company.</strong>
          </p>
          <p>
            WordPress stands as one of the most versatile and user-friendly content management systems
            available today. It offers a robust platform for both beginners and seasoned developers, making it
            an ideal choice for such projects. The combination of user-friendliness, flexibility, and strong
            community support makes WordPress an excellent foundation for this project, ensuring that the
            website is not only beautifully designed and functional but also future-proof and easy to
            maintain.
          </p>
        </>
      ),
      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/st-website/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/st-website/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/st-website/" + "mobile.webp",
      },
    },
    relatedProjects: ["st-booking", "st-video", "st-ref"],
  },
  {
    slug: "hch-admin",
    name: "HeartCore Hotels CMS",
    shortDescription:
      "Fully custom CMS for HeartCore Hotels. Lightweight, and fast. The backend part is built on Adonis.js as REST API application and the admin part is built on Angular as a SPA.",
    preview: PROJECTS_IMAGES_PATH + "/hch-admin/" + "preview.webp",
    year: 2022,
    private: true,
    priority: true,
    developedFor: "HeartCore Hotels",
    role: "Full-stack",
    tags: [
      "TypeScript",
      "Adonis.js",
      "Angular",
      "Angular Material IU",
      "REST API",
      "Bitbucket",
      "Bitbucket Pipelines",
      "AWS",
    ],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/hch-admin/" + "full.webp",
      fullDescription: (
        <>
          <p>
            <strong>Fully custom CMS for HeartCore Hotels.</strong>
          </p>
          <p>
            The backend part is built on Adonis.js as REST API application. The admin part is built on Angular
            as a SPA.
          </p>
          <p>User can manage the following entities:</p>
          <ul>
            <li>
              <strong>Hotels: </strong>Basic CRUD operations, attaching a location and available services,
              managing user's testimonials.
            </li>
            <li>
              <strong>Blog: </strong>Basic CRUD operations for articles, attaching a category and tags.
            </li>
            <li>
              <strong>Users: </strong>Basic CRUD operations for users. Manage their roles and permissions.
            </li>
            <li>
              <strong>Orders: </strong>Basic CRUD operations for orders. Manage order status.
            </li>
            <li>
              <strong>Settings: </strong>Manage the site options. Each option is presented as json object and
              can be modified using unique custom fields mechanism. This mechanism allows the user to create
              an option with any structure, like a simple string, array, object, repeater, etc.
            </li>
            <li>
              <strong>Media library: </strong>Manage the media files. Upload, delete, and view the files. The
              user can attach the media files to the hotel, blog, or any other entity.
            </li>
          </ul>
        </>
      ),
      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/hch-admin/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/hch-admin/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/hch-admin/" + "mobile.webp",
      },
    },
    relatedProjects: ["hch-site"],
  },
  {
    slug: "hch-site",
    name: "HeartCore Hotels website",
    shortDescription:
      "Fully custom CMS for HeartCore Hotels. SEO optimized, lightweight, and fast. The client part is built on Adonis.js as classic web application and the admin part is built on Angular as a SPA. The both parts are fully responsive and works on all devices.",
    preview: PROJECTS_IMAGES_PATH + "/hch-site/" + "preview.webp",
    year: 2022,
    private: false,
    priority: true,
    developedFor: "HeartCore Hotels Website",
    role: "Full-stack",
    link: "https://www.heartcorehotels.com",
    tags: [
      "Typescript",
      "Adonis.js",
      "Bootstrap",
      "Sirvoy API",
      "Google maps API",
      "Bitbucket",
      "Bitbucket Pipelines",
      "AWS",
    ],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/hch-site/" + "full.webp",
      fullDescription: (
        <>
          <p>
            <strong>HeartCore Hotels website.</strong>
          </p>
          <p>
            The client part is built on Adonis.js as classic web application. The site is fully SEO optimized,
            lightweight, and fast. The site is multilingual and works on all devices.
          </p>
          <p>
            Users can book a room in the hotel, view the hotel's services, and contact the hotel. They can
            also register and log in to the site, view their booking history, and manage their profile and
            orders.
          </p>
        </>
      ),
      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/hch-site/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/hch-site/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/hch-site/" + "mobile.webp",
      },
    },
    relatedProjects: ["hch-admin"],
  },
  {
    slug: "clear-view",
    name: "ClearView",
    shortDescription:
      "An application for collecting, processing and storing Google search results by saved keywords on a daily basis.",
    preview: PROJECTS_IMAGES_PATH + "/clear-view/" + "preview.webp",
    year: 2021,
    private: true,
    priority: true,
    developedFor: "Private client",
    role: "Front-end",
    tags: [
      "Typescript",
      "Adonis.js",
      "Angular",
      "Angular Material IU",
      "REST API",
      "Bitbucket",
      "Bitbucket Pipelines",
    ],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/clear-view/" + "full.webp",
      fullDescription: (
        <>
          <p>
            ClearView is a private web application that collects and processes Google search results by saved
            keywords on a daily basis. The application is built on Adonis.js (backend, REST API) and Angular
            (frontend part, SPA).
          </p>
          <p>
            Using Cron jobs, the application collects search results from Google, parse and stores them in the
            database. Each section of the search result (like "knowledge block", "Twitter block", "Youtube
            videos" etc.) is stored in the database as a separate entity. The user can view the search results
            in the form of a table, filter them by date, and export them to a JPEG/PNG file (as a screenshot).
            Each search result is also saved as separate .html file and available for preview.
          </p>
          <p>The application is fully responsive and works on all devices.</p>
        </>
      ),
      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/clear-view/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/clear-view/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/clear-view/" + "mobile.webp",
      },
    },
  },
  {
    slug: "hailopay",
    name: "Hailopay fundraising platform",
    shortDescription:
      "Hailopay is a fundraising platform that allows users to create fundraising campaigns and collect donations. The platform is built on Angular (frontend part, SPA).",
    preview: PROJECTS_IMAGES_PATH + "/hailopay/" + "preview.webp",
    year: 2021,
    private: false,
    priority: false,
    developedFor: "Javelin",
    link: "https://hailopay.ie",
    role: "Front-end",
    tags: ["TypeScript", "Angular", "Angular Universal", "Angular Material IU"],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/hailopay/" + "full.webp",
      fullDescription: (
        <>
          <p>
            <strong>Fundraising platform.</strong>
          </p>
          <p>
            Hailopay is a fundraising platform that allows users to create fundraising campaigns and collect
            donations. To ensure SEO optimization, the site was built on the basis of Angular using Server
            Side Rendering technology (Angular Universal).
          </p>
        </>
      ),
      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/hailopay/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/hailopay/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/hailopay/" + "mobile.webp",
      },
    },
  },
  {
    slug: "first-bread",
    name: "First Bread website",
    shortDescription:
      "The site represents a company that produces and sells bread. Custom designed theme for Wordpress. SEO optimized and fast.",
    preview: PROJECTS_IMAGES_PATH + "/first-bread/" + "preview.webp",
    year: 2020,
    private: false,
    priority: true,
    role: "Full-stack",
    developedFor: "HD-group",
    link: "https://hlib.cv.ua",
    tags: ["JavaScript", "PHP", "Wordpress", "Bootstrap", "SCSS", "Webpack", "npm", "Google maps API"],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/first-bread/" + "full.webp",
      fullDescription: (
        <>
          <p>
            <strong>Website for presentation of "First bread" company products</strong>
          </p>
          <p>
            WordPress stands as one of the most versatile and user-friendly content management systems
            available today. It offers a robust platform for both beginners and seasoned developers, making it
            an ideal choice for such projects. The combination of user-friendliness, flexibility, and strong
            community support makes WordPress an excellent foundation for this project, ensuring that the
            website is not only beautifully designed and functional but also future-proof and easy to
            maintain.
          </p>
        </>
      ),
      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/first-bread/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/first-bread/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/first-bread/" + "mobile.webp",
      },
    },
    relatedProjects: ["bread-4u", "hlebodar"],
  },
  {
    slug: "hlebodar",
    name: "Hlebodar website",
    shortDescription:
      "Multi-language site of Hlebodar company. Custom designed theme for Wordpress. SEO optimized and fast. The site is fully responsive and works on all devices.",
    preview: PROJECTS_IMAGES_PATH + "/hlebodar/" + "preview.webp",
    year: 2020,
    private: false,
    priority: true,
    role: "Full-stack",
    developedFor: "HD-group",
    link: "https://hlibodar.com.ua/en",
    tags: ["JavaScript", "PHP", "Wordpress", "Bootstrap", "SCSS", "Webpack", "npm", "Google maps API"],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/hlebodar/" + "full.webp",
      fullDescription: (
        <>
          <p>
            <strong>Multi-language website for presentation of "Hlebodar" company products</strong>
          </p>
          <p>
            WordPress stands as one of the most versatile and user-friendly content management systems
            available today. It offers a robust platform for both beginners and seasoned developers, making it
            an ideal choice for such projects. The combination of user-friendliness, flexibility, and strong
            community support makes WordPress an excellent foundation for this project, ensuring that the
            website is not only beautifully designed and functional but also future-proof and easy to
            maintain.
          </p>
        </>
      ),
      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/hlebodar/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/hlebodar/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/hlebodar/" + "mobile.webp",
      },
    },
    relatedProjects: ["bread-4u", "first-bread"],
  },
  {
    slug: "bread-4u",
    name: "Bread4U landing pages",
    shortDescription:
      "Landing pages for Bread4U company. SEO optimized and fast. The page is fully responsive and works on all devices.",
    preview: PROJECTS_IMAGES_PATH + "/bread-4u/" + "preview.webp",
    year: 2019,
    private: false,
    priority: false,
    role: "Front-end",
    developedFor: "HD-group",
    link: "https://www.bread4u.com.ua",
    tags: ["JavaScript", "HTML", "Bootstrap", "SCSS", "Webpack", "npm", "Google maps API"],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/bread-4u/" + "full.webp",
      fullDescription: (
        <>
          <p>
            <strong>Landing pages for Bread4U product line of "Hlebodar Group" company.</strong>
          </p>
          <p>SEO optimized and fast. The site is fully responsive and works on all devices</p>
        </>
      ),

      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/bread-4u/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/bread-4u/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/bread-4u/" + "mobile.webp",
      },
    },
    relatedProjects: ["hlebodar", "first-bread"],
  },
  {
    slug: "deinsekt",
    name: "Online store Deinsekt",
    shortDescription:
      "Online store that sells wines. The user has the option to select the bottle label depending on the special event.",
    preview: PROJECTS_IMAGES_PATH + "/deinsekt/" + "preview.webp",
    year: 2019,
    private: false,
    priority: true,
    role: "Full-stack",
    developedFor: "Deinsekt.de",
    link: "https://www.deinsekt.de",
    tags: ["JavaScript", "Wordpress", "Elementor", "WooCommerce", "Bootstrap", "SCSS"],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/deinsekt/" + "full.webp",
      fullDescription: (
        <>
          <p>Online Wines store.</p>
          <p>
            Taking into account the client’s desire to maintain this site without programming skills, we chose
            Elementor plugin to build the site. This plugin allows the client to easily edit the site without
            any programming skills. The user has the option to select the bottle label depending on the
            special event.
          </p>
        </>
      ),
      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/deinsekt/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/deinsekt/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/deinsekt/" + "mobile.webp",
      },
    },
  },
  {
    slug: "codevery",
    name: "Codevery site",
    shortDescription:
      "Website of the Codevery company. Custom designed theme for Wordpress. SEO optimized and fast. The site is fully responsive and works on all devices.",
    preview: PROJECTS_IMAGES_PATH + "/codevery/" + "preview.webp",
    year: 2019,
    private: false,
    priority: true,
    role: "Full-stack",
    developedFor: "Codevery LLC",
    link: "https://codevery.com/portfolio",
    tags: ["JavaScript", "PHP", "Wordpress", "Bootstrap", "SCSS", "Webpack", "npm"],
    detailedInfo: {
      fillImage: PROJECTS_IMAGES_PATH + "/codevery/" + "full.webp",
      fullDescription: (
        <>
          <p>
            <strong>Website of the Codevery company.</strong>
          </p>
          <p>
            WordPress stands as one of the most versatile and user-friendly content management systems
            available today. It offers a robust platform for both beginners and seasoned developers, making it
            an ideal choice for such projects. The combination of user-friendliness, flexibility, and strong
            community support makes WordPress an excellent foundation for this project, ensuring that the
            website is not only beautifully designed and functional but also future-proof and easy to
            maintain.
          </p>
          <p>
            There is an opinion that WordPress is slow and not productive. But it is not true. The speed of
            the site depends on the quality of the code and used approaches. We used the best practices to
            make the site fast and productive.
          </p>
        </>
      ),
      devices: {
        desktop: PROJECTS_IMAGES_PATH + "/codevery/" + "desktop.webp",
        tablet: PROJECTS_IMAGES_PATH + "/codevery/" + "tablet.webp",
        mobile: PROJECTS_IMAGES_PATH + "/codevery/" + "mobile.webp",
      },
    },
  },
];
